import '../imports/api/posts/methods';
import '../imports/api/posts/publication';
import '../imports/api/posts/posts';
import '../imports/api/accounts/publication'
import '../imports/api/accounts/methods'
import '../imports/api/departments/publication'
import '../imports/api/departments/methods'
import '../imports/api/leaders/publication'
import '../imports/api/leaders/methods'